### ISSUE TITLE
difference() behaves unexpectedly

### ISSUE THREAD

**Issue by paulmelnikow** [strongpauly/BetterSet#3]
I used `difference()` for the first time and it's not doing what I expected. The "difference" between two sets is the relative complement. (Here's the [wikipedia article](https://en.wikipedia.org/wiki/Complement_(set_theory)). That article further lists [several programming languages](https://en.wikipedia.org/wiki/Complement_(set_theory)#Complements_in_various_programming_languages) which also refer to this operation as the "difference."

My teammate and I both found this behavior very confusing.

The symmetric difference is of course also a thing, and seems like a useful operation to provide as well. I've always called that the disjunctive union which I think conveys the idea more clearly.

Would you consider renaming `complement` to `difference`, and `difference` to either `symmetricDifference` or `disjunctiveUnion`?

Of course a breaking change needs to be weighed heavily. In this case we're avoiding developer surprise. I think avoiding developer surprise is especially important for a library like this, which doesn't do much more than provide a useful interface atop one which is less useful.

**Comment by strongpauly** [comment]
I'm looking at it now.  The comment on the function does specify that it is the **symmetric difference** as described in this [wikipedia article](https://en.wikipedia.org/wiki/Symmetric_difference), but I can understand the confusion.  I think my reasoning was to try and keep the function names concise, and as you're never going to be able to calculate an absolute complement, that free'd up `complement`, which left `difference` for symmetric difference.

As you say, breaking changes do need to be weighed heavily.  What I may do for the next release is deprecate `difference` and create a `disjunctiveUnion`
